version: '3'

networks:
  benetwork:
    name: benetwork
    external: true

services:
  monitoringwebdb:
    container_name: monitoringwebdb
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1436:1433"
    environment:
      - SA_PASSWORD=Pasword@12345#
      - ACCEPT_EULA=Y
    networks:
      - benetwork
  
  monitoringserverapp:
    container_name: monitoring-management-app
    image: ${DOCKER_REGISTRY-}monitoringserverapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7202:80"
    depends_on: 
        - monitoringwebdb
    environment:
      - DB_HOST=monitoringwebdb
      - DB_NAME=monitoringManagement
      - DB_USER=sa
      - DB_SA_PASSWORD=Pasword@12345#
    networks:
      - benetwork