// <auto-generated />
using System;
using DevicesManagementData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevicesManagementData.Migrations
{
    [DbContext(typeof(DeviceManagementContext))]
    [Migration("20231028081913_addAddressAsString")]
    partial class addAddressAsString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevicesManagementDomain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MaximuHourlyEnergyConsumption")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b2edfe4-0c00-48bf-9a4a-fef366810789"),
                            Description = "eco-friendly",
                            MaximuHourlyEnergyConsumption = 10L,
                            Name = "Air Conditioner"
                        },
                        new
                        {
                            Id = new Guid("dc26c5e2-91b2-4193-a044-f48e6b1e3a9f"),
                            Description = "An energy-efficient dishwasher",
                            MaximuHourlyEnergyConsumption = 6L,
                            Name = "Dishwasher"
                        },
                        new
                        {
                            Id = new Guid("12161baa-f126-4211-b8cd-23a7b535fbc7"),
                            Description = "just an inch of water a week",
                            MaximuHourlyEnergyConsumption = 1L,
                            Name = " Smart sprinkler"
                        },
                        new
                        {
                            Id = new Guid("ca7dc133-d5f6-47cd-86ec-551f0250633b"),
                            Description = "store rainwater.",
                            MaximuHourlyEnergyConsumption = 3L,
                            Name = "Rain barrels"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("434be442-555c-4991-8cac-9c4fa3e4b4a4"),
                            Email = "floreaneusebiu@gmail.com",
                            Name = "Eusebiu"
                        },
                        new
                        {
                            Id = new Guid("0be6f0cf-d278-4591-bc10-500d2565ad09"),
                            Email = "razvanb@yahoo.com",
                            Name = "Razvan"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.UserDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("DevicesManagementDomain.UserDevice", b =>
                {
                    b.HasOne("DevicesManagementDomain.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevicesManagementDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevicesManagementDomain.Device", b =>
                {
                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
