// <auto-generated />
using System;
using DevicesManagementData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevicesManagementData.Migrations
{
    [DbContext(typeof(DeviceManagementContext))]
    [Migration("20231029215445_addSimplePkToUserDevice")]
    partial class addSimplePkToUserDevice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevicesManagementDomain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MaximuHourlyEnergyConsumption")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9719778b-f8c7-4a7c-bcd6-893bcf04c9db"),
                            Description = "eco-friendly",
                            MaximuHourlyEnergyConsumption = 10L,
                            Name = "Air Conditioner"
                        },
                        new
                        {
                            Id = new Guid("faf982b2-c26a-45e5-b794-d3246db752a1"),
                            Description = "An energy-efficient dishwasher",
                            MaximuHourlyEnergyConsumption = 6L,
                            Name = "Dishwasher"
                        },
                        new
                        {
                            Id = new Guid("eb593e4f-1dff-4ef3-acd4-55ed1f69c819"),
                            Description = "just an inch of water a week",
                            MaximuHourlyEnergyConsumption = 1L,
                            Name = " Smart sprinkler"
                        },
                        new
                        {
                            Id = new Guid("9da63984-b01f-4f57-a360-c6f9e3277f20"),
                            Description = "store rainwater.",
                            MaximuHourlyEnergyConsumption = 3L,
                            Name = "Rain barrels"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b634507d-6eed-4f20-aef1-7c5647973523"),
                            Email = "floreaneusebiu@gmail.com",
                            Name = "Eusebiu"
                        },
                        new
                        {
                            Id = new Guid("439a5955-08b0-4556-8569-0388dc30e0eb"),
                            Email = "razvanb@yahoo.com",
                            Name = "Razvan"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("DevicesManagementDomain.UserDevice", b =>
                {
                    b.HasOne("DevicesManagementDomain.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevicesManagementDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevicesManagementDomain.Device", b =>
                {
                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
