// <auto-generated />
using System;
using DevicesManagementData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevicesManagementData.Migrations
{
    [DbContext(typeof(DeviceManagementContext))]
    [Migration("20231026064710_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevicesManagementDomain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("437ff9e8-4486-400f-bdd7-0ed41d4fafc3"),
                            City = "Lincoln",
                            Country = "United States",
                            Street = "Main Street"
                        },
                        new
                        {
                            Id = new Guid("d247048b-4f67-40ad-a4eb-5ba66c86b121"),
                            City = "Lincoln",
                            Country = "United States",
                            Street = "Main Street"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MaximuHourlyEnergyConsumption")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75704484-90e2-459d-83f8-dc31c597e4b4"),
                            Description = "eco-friendly",
                            MaximuHourlyEnergyConsumption = 10L,
                            Name = "Air Conditioner"
                        },
                        new
                        {
                            Id = new Guid("736aafec-3b03-44fb-82cd-9659ac324590"),
                            Description = "An energy-efficient dishwasher",
                            MaximuHourlyEnergyConsumption = 6L,
                            Name = "Dishwasher"
                        },
                        new
                        {
                            Id = new Guid("7ee04232-7e0b-4727-90bd-f6f20980ba7c"),
                            Description = "just an inch of water a week",
                            MaximuHourlyEnergyConsumption = 1L,
                            Name = " Smart sprinkler"
                        },
                        new
                        {
                            Id = new Guid("65911a4f-b4c1-41bc-9055-428c1f6eef50"),
                            Description = "store rainwater.",
                            MaximuHourlyEnergyConsumption = 3L,
                            Name = "Rain barrels"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("869b2319-f986-41a2-bd1a-a6966599d062"),
                            Email = "floreaneusebiu@gmail.com",
                            Name = "Eusebiu"
                        },
                        new
                        {
                            Id = new Guid("16bf1586-6195-441e-9ec1-c2a05373388a"),
                            Email = "razvanb@yahoo.com",
                            Name = "Razvan"
                        });
                });

            modelBuilder.Entity("DevicesManagementDomain.UserDevice", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "DeviceId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DeviceId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("DevicesManagementDomain.UserDevice", b =>
                {
                    b.HasOne("DevicesManagementDomain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevicesManagementDomain.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevicesManagementDomain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevicesManagementDomain.Device", b =>
                {
                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
