version: '3'

networks:
  benetwork:
    name: benetwork
    external: true

services:
  deviceswebdb:
    container_name: deviceswebdb
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1437:1433"
    environment:
      - SA_PASSWORD=Pasword@12345#
      - ACCEPT_EULA=Y
    networks:
      - benetwork
  
  devicesserverapp:
    container_name: devices-management-app
    image: ${DOCKER_REGISTRY-}devicesserverapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7200:80"
    depends_on: 
        - deviceswebdb
    environment:
      - DB_HOST=deviceswebdb
      - DB_NAME=devicesManagement
      - DB_USER=sa
      - DB_SA_PASSWORD=Pasword@12345#
    networks:
      - benetwork