version: '3'

networks:
  benetwork:
    name: benetwork
    external: true

services:
  userswebdb:
    container_name: userswebdb
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1435:1433"
    environment:
      - SA_PASSWORD=Pasword@12345#
      - ACCEPT_EULA=Y
    networks:
      - benetwork
  
  usersserverapp:
    container_name: users-management-app
    image: ${DOCKER_REGISTRY-}usersserverapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7201:80"
    depends_on: 
        - userswebdb
    environment:
      - DB_HOST=userswebdb
      - DB_NAME=usersManagement
      - DB_USER=sa
      - DB_SA_PASSWORD=Pasword@12345#
    networks:
      - benetwork